# Generated by Django 5.0.6 on 2024-06-01 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='descriptin',
            new_name='description',
        ),
    ]
